const APPROVE_NOTIFICATION_SINGLE = 'singleApproveNotify';
const REJECT_NOTIFICATION_SINGLE = 'singleRejectNotify';
const ID_MISMATCH_NOTIFICATION_SINGLE = 'singleIdMismatchNotify';
const REJECT_NOTIFICATION_BULK = 'bulkRejectionNotify';
const ID_MISMATCH_NOTIFICATION_BULK ='bulkIdMismatchNotify';
const VENUE_UPDATE_NOTIFICATION_BULK = 'venueUpdate';
const REMINDER_NOTIFICATION_BULK = 'remainderNotify';
module.exports = 
{
    APPROVE_NOTIFICATION_SINGLE:APPROVE_NOTIFICATION_SINGLE,
    REJECT_NOTIFICATION_SINGLE:REJECT_NOTIFICATION_SINGLE,
    ID_MISMATCH_NOTIFICATION_SINGLE:ID_MISMATCH_NOTIFICATION_SINGLE,
    REJECT_NOTIFICATION_BULK:REJECT_NOTIFICATION_BULK,
    ID_MISMATCH_NOTIFICATION_BULK:ID_MISMATCH_NOTIFICATION_BULK,
    VENUE_UPDATE_NOTIFICATION_BULK:VENUE_UPDATE_NOTIFICATION_BULK,
    REMINDER_NOTIFICATION_BULK:REMINDER_NOTIFICATION_BULK
};