const INVALID_USER = "INVALID USER";
const ERROR_DB = "CAN'T CONNECT TO DATABASE.PLEASE TRY AFTER SOMETIME.";
const USER_ROLE_NS = "USER ROLE NOT SET";
const LOGIN_S = "LOGED IN SUCCESSFULLY"


module.exports = {
    INVALID_USER,
    ERROR_DB,
    USER_ROLE_NS,
    LOGIN_S,
}